version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tareas_crehana
      POSTGRES_USER: crehana_user
      POSTGRES_PASSWORD: 586247931
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
